region: eu-west-1

function_name: python-bot
handler: service.handler
description: Slack bot made with python
runtime: python3.7
role: python-bot-role

# S3 upload requires appropriate role with s3:PutObject permission
# (ex. basic_s3_upload), a destination bucket, and the key prefix
# bucket_name: 'example-bucket'
# s3_key_prefix: 'path/to/file/'

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
#aws_access_key_id:
#aws_secret_access_key:

# dist_directory: dist
# timeout: 15
# memory_size: 512
# concurrency: 500
#

# Experimental Environment variables
environment_variables:
    BOT_TOKEN: AQICAHhAHn+NvzUeWK9HEnLbPWR6Zw0L8wVNzJgOh5lgS9XeKQFDWpJ9xobEVaaP57fy3TwhAAAAmDCBlQYJKoZIhvcNAQcGoIGHMIGEAgEAMH8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0yPn+eBJiXdZ9kjgAgEQgFKHlbCNLGbViN/6FiIztXDX6A4BNTjc6LPESmUvulyCWUEAH8b7+A8D3lyUQB+gZjmqIGXJ2PzBVY5JCGhSvMnCLvHkpK4pAU1lrBZRrX0QW6Zx

# If `tags` is uncommented then tags will be set at creation or update
# time.  During an update all other tags will be removed except the tags
# listed here.
#tags:
#    tag_1: foo
#    tag_2: bar

# Build options
build:
  source_directories: lib # a comma delimited list of directories in your project root that contains source to package.
